import type { AppClassification, Settings } from '../../shared/types';

// Default application settings
export const DEFAULT_SETTINGS: Settings = {
  // Tracking
  tracking_interval_ms: 3000,     // poll every 3 seconds
  idle_threshold_seconds: 120,    // 2 minutes idle = idle state
  enable_browser_tracking: true,

  // Ollama (local)
  ollama_endpoint: 'http://localhost:11434',
  ollama_model: 'phi4-mini:latest',

  // AI provider
  ai_provider: 'ollama',
  claude_api_key: '',
  openai_api_key: '',
  language_model: 'claude-sonnet-4-6', // default for cloud providers
  enable_llm: true,

  // Vision — disabled by default. Most new users won't have the model installed.
  // Enable in Settings → AI → Vision Analysis after pulling a vision model via Ollama.
  vision_enabled: false,
  vision_model: 'minicpm-v:2.6',  // best screen/text reading in its size class (~5.5 GB)

  // Notifications
  enable_focus_notifications: true,
  daily_focus_target_minutes: 120,

  onboarding_completed: false,

  // Appearance
  theme: 'system',
};

// ─── Default classification rules ─────────────────────────────────────────────
// pattern_type='app'    → matches against active application name
// pattern_type='domain' → matches against browser domain
// pattern_type='title'  → matches against window title (substring)

export const DEFAULT_CLASSIFICATIONS: Omit<AppClassification, 'id'>[] = [
  // ── Distracting domains ──────────────────────────────────────────────────
  { pattern: 'youtube.com',      pattern_type: 'domain', classification: 'distracting', reason: 'Video entertainment', is_default: 1 },
  { pattern: 'twitter.com',      pattern_type: 'domain', classification: 'distracting', reason: 'Social media',       is_default: 1 },
  { pattern: 'x.com',            pattern_type: 'domain', classification: 'distracting', reason: 'Social media',       is_default: 1 },
  { pattern: 'reddit.com',       pattern_type: 'domain', classification: 'distracting', reason: 'Social media',       is_default: 1 },
  { pattern: 'facebook.com',     pattern_type: 'domain', classification: 'distracting', reason: 'Social media',       is_default: 1 },
  { pattern: 'instagram.com',    pattern_type: 'domain', classification: 'distracting', reason: 'Social media',       is_default: 1 },
  { pattern: 'tiktok.com',       pattern_type: 'domain', classification: 'distracting', reason: 'Social media',       is_default: 1 },
  { pattern: 'netflix.com',      pattern_type: 'domain', classification: 'distracting', reason: 'Video streaming',    is_default: 1 },
  { pattern: 'twitch.tv',        pattern_type: 'domain', classification: 'distracting', reason: 'Video streaming',    is_default: 1 },
  { pattern: 'hulu.com',         pattern_type: 'domain', classification: 'distracting', reason: 'Video streaming',    is_default: 1 },
  { pattern: 'disneyplus.com',   pattern_type: 'domain', classification: 'distracting', reason: 'Video streaming',    is_default: 1 },
  { pattern: 'amazon.com',       pattern_type: 'domain', classification: 'distracting', reason: 'Online shopping',    is_default: 1 },
  { pattern: 'ebay.com',         pattern_type: 'domain', classification: 'distracting', reason: 'Online shopping',    is_default: 1 },
  { pattern: 'linkedin.com',     pattern_type: 'domain', classification: 'neutral',     reason: 'Professional social',is_default: 1 },
  { pattern: 'news.ycombinator.com', pattern_type: 'domain', classification: 'neutral', reason: 'Tech news',         is_default: 1 },

  // ── Productive domains ───────────────────────────────────────────────────
  { pattern: 'github.com',       pattern_type: 'domain', classification: 'productive', reason: 'Code hosting',       is_default: 1 },
  { pattern: 'gitlab.com',       pattern_type: 'domain', classification: 'productive', reason: 'Code hosting',       is_default: 1 },
  { pattern: 'stackoverflow.com',pattern_type: 'domain', classification: 'productive', reason: 'Developer Q&A',      is_default: 1 },
  { pattern: 'npmjs.com',        pattern_type: 'domain', classification: 'productive', reason: 'Package registry',   is_default: 1 },
  { pattern: 'docs.',            pattern_type: 'domain', classification: 'productive', reason: 'Documentation',      is_default: 1 },
  { pattern: 'developer.',       pattern_type: 'domain', classification: 'productive', reason: 'Developer docs',     is_default: 1 },
  { pattern: 'mdn',              pattern_type: 'domain', classification: 'productive', reason: 'Web docs',           is_default: 1 },
  { pattern: 'notion.so',        pattern_type: 'domain', classification: 'productive', reason: 'Notes & docs',       is_default: 1 },
  { pattern: 'linear.app',       pattern_type: 'domain', classification: 'productive', reason: 'Project management', is_default: 1 },
  { pattern: 'figma.com',        pattern_type: 'domain', classification: 'productive', reason: 'Design tool',        is_default: 1 },
  { pattern: 'vercel.com',       pattern_type: 'domain', classification: 'productive', reason: 'Deployment',         is_default: 1 },

  // ── AI assistants (highly productive when used for work) ─────────────────
  { pattern: 'chat.openai.com', pattern_type: 'domain', classification: 'productive', reason: 'AI assistant', is_default: 1 },
  { pattern: 'chatgpt.com',     pattern_type: 'domain', classification: 'productive', reason: 'AI assistant', is_default: 1 },
  { pattern: 'claude.ai',       pattern_type: 'domain', classification: 'productive', reason: 'AI assistant', is_default: 1 },
  { pattern: 'perplexity.ai',   pattern_type: 'domain', classification: 'productive', reason: 'AI research',  is_default: 1 },
  { pattern: 'gemini.google.com', pattern_type: 'domain', classification: 'productive', reason: 'AI assistant', is_default: 1 },
  { pattern: 'phind.com',       pattern_type: 'domain', classification: 'productive', reason: 'AI coding',    is_default: 1 },
  { pattern: 'cursor.sh',       pattern_type: 'domain', classification: 'productive', reason: 'AI coding',    is_default: 1 },
  // ── More productive domains ───────────────────────────────────────────────
  { pattern: 'loom.com',        pattern_type: 'domain', classification: 'productive', reason: 'Video communication', is_default: 1 },
  { pattern: 'excalidraw.com',  pattern_type: 'domain', classification: 'productive', reason: 'Diagramming', is_default: 1 },
  { pattern: 'miro.com',        pattern_type: 'domain', classification: 'productive', reason: 'Whiteboarding', is_default: 1 },
  { pattern: 'airtable.com',    pattern_type: 'domain', classification: 'productive', reason: 'Data management', is_default: 1 },
  { pattern: 'jira.atlassian',  pattern_type: 'domain', classification: 'productive', reason: 'Project management', is_default: 1 },
  { pattern: 'confluence',      pattern_type: 'domain', classification: 'productive', reason: 'Documentation', is_default: 1 },
  { pattern: 'trello.com',      pattern_type: 'domain', classification: 'productive', reason: 'Project management', is_default: 1 },
  { pattern: 'asana.com',       pattern_type: 'domain', classification: 'productive', reason: 'Task management', is_default: 1 },
  { pattern: 'monday.com',      pattern_type: 'domain', classification: 'productive', reason: 'Project management', is_default: 1 },
  { pattern: 'clickup.com',     pattern_type: 'domain', classification: 'productive', reason: 'Project management', is_default: 1 },
  { pattern: 'height.app',      pattern_type: 'domain', classification: 'productive', reason: 'Project management', is_default: 1 },
  { pattern: 'supabase.com',    pattern_type: 'domain', classification: 'productive', reason: 'Backend platform', is_default: 1 },
  { pattern: 'supabase.io',     pattern_type: 'domain', classification: 'productive', reason: 'Backend platform', is_default: 1 },
  { pattern: 'railway.app',     pattern_type: 'domain', classification: 'productive', reason: 'Deployment', is_default: 1 },
  { pattern: 'render.com',      pattern_type: 'domain', classification: 'productive', reason: 'Deployment', is_default: 1 },
  { pattern: 'netlify.com',     pattern_type: 'domain', classification: 'productive', reason: 'Deployment', is_default: 1 },
  { pattern: 'fly.io',          pattern_type: 'domain', classification: 'productive', reason: 'Deployment', is_default: 1 },
  { pattern: 'heroku.com',      pattern_type: 'domain', classification: 'productive', reason: 'Cloud platform', is_default: 1 },
  { pattern: 'aws.amazon.com',  pattern_type: 'domain', classification: 'productive', reason: 'Cloud platform', is_default: 1 },
  { pattern: 'console.aws',     pattern_type: 'domain', classification: 'productive', reason: 'Cloud console', is_default: 1 },
  { pattern: 'cloud.google.com',pattern_type: 'domain', classification: 'productive', reason: 'Cloud platform', is_default: 1 },
  { pattern: 'firebase.google', pattern_type: 'domain', classification: 'productive', reason: 'Firebase', is_default: 1 },
  { pattern: 'azure.microsoft', pattern_type: 'domain', classification: 'productive', reason: 'Cloud platform', is_default: 1 },
  { pattern: 'codesandbox.io',  pattern_type: 'domain', classification: 'productive', reason: 'Online IDE', is_default: 1 },
  { pattern: 'codepen.io',      pattern_type: 'domain', classification: 'productive', reason: 'Online IDE', is_default: 1 },
  { pattern: 'replit.com',      pattern_type: 'domain', classification: 'productive', reason: 'Online IDE', is_default: 1 },
  { pattern: 'stackblitz.com',  pattern_type: 'domain', classification: 'productive', reason: 'Online IDE', is_default: 1 },
  { pattern: 'leetcode.com',    pattern_type: 'domain', classification: 'productive', reason: 'Coding practice', is_default: 1 },
  { pattern: 'hackerrank.com',  pattern_type: 'domain', classification: 'productive', reason: 'Coding practice', is_default: 1 },
  { pattern: 'freecodecamp.org',pattern_type: 'domain', classification: 'productive', reason: 'Learning', is_default: 1 },
  { pattern: 'bitbucket.org',   pattern_type: 'domain', classification: 'productive', reason: 'Code hosting', is_default: 1 },
  { pattern: 'circleci.com',    pattern_type: 'domain', classification: 'productive', reason: 'CI/CD', is_default: 1 },
  { pattern: 'app.circleci.com',pattern_type: 'domain', classification: 'productive', reason: 'CI/CD', is_default: 1 },
  { pattern: 'sentry.io',       pattern_type: 'domain', classification: 'productive', reason: 'Error tracking', is_default: 1 },
  { pattern: 'datadog',         pattern_type: 'domain', classification: 'productive', reason: 'Monitoring', is_default: 1 },
  { pattern: 'grafana',         pattern_type: 'domain', classification: 'productive', reason: 'Monitoring', is_default: 1 },
  { pattern: 'stripe.com',      pattern_type: 'domain', classification: 'productive', reason: 'Payments', is_default: 1 },
  { pattern: 'dashboard.stripe',pattern_type: 'domain', classification: 'productive', reason: 'Payments dashboard', is_default: 1 },
  { pattern: 'zapier.com',      pattern_type: 'domain', classification: 'productive', reason: 'Automation', is_default: 1 },
  { pattern: 'make.com',        pattern_type: 'domain', classification: 'productive', reason: 'Automation', is_default: 1 },
  { pattern: 'typeform.com',    pattern_type: 'domain', classification: 'productive', reason: 'Forms', is_default: 1 },
  { pattern: 'codeium.com',     pattern_type: 'domain', classification: 'productive', reason: 'AI coding', is_default: 1 },
  { pattern: 'v0.dev',          pattern_type: 'domain', classification: 'productive', reason: 'AI coding', is_default: 1 },
  { pattern: 'bolt.new',        pattern_type: 'domain', classification: 'productive', reason: 'AI coding', is_default: 1 },
  // ── Neutral/learning domains ──────────────────────────────────────────────
  { pattern: 'medium.com',      pattern_type: 'domain', classification: 'neutral', reason: 'Reading', is_default: 1 },
  { pattern: 'substack.com',    pattern_type: 'domain', classification: 'neutral', reason: 'Reading', is_default: 1 },
  { pattern: 'hashnode.com',    pattern_type: 'domain', classification: 'neutral', reason: 'Reading', is_default: 1 },
  { pattern: 'dev.to',          pattern_type: 'domain', classification: 'neutral', reason: 'Tech reading', is_default: 1 },
  { pattern: 'udemy.com',       pattern_type: 'domain', classification: 'neutral', reason: 'Learning', is_default: 1 },
  { pattern: 'coursera.org',    pattern_type: 'domain', classification: 'neutral', reason: 'Learning', is_default: 1 },
  { pattern: 'udacity.com',     pattern_type: 'domain', classification: 'neutral', reason: 'Learning', is_default: 1 },
  { pattern: 'pluralsight.com', pattern_type: 'domain', classification: 'neutral', reason: 'Learning', is_default: 1 },
  { pattern: 'egghead.io',      pattern_type: 'domain', classification: 'neutral', reason: 'Learning', is_default: 1 },
  { pattern: 'frontendmasters', pattern_type: 'domain', classification: 'neutral', reason: 'Learning', is_default: 1 },

  // ── Productive apps ───────────────────────────────────────────────────────
  { pattern: 'Code',             pattern_type: 'app', classification: 'productive', reason: 'VS Code',               is_default: 1 },
  { pattern: 'Visual Studio Code',pattern_type:'app', classification: 'productive', reason: 'VS Code',               is_default: 1 },
  { pattern: 'Cursor',           pattern_type: 'app', classification: 'productive', reason: 'AI Code Editor',        is_default: 1 },
  { pattern: 'Xcode',            pattern_type: 'app', classification: 'productive', reason: 'Apple IDE',             is_default: 1 },
  { pattern: 'Terminal',         pattern_type: 'app', classification: 'productive', reason: 'Command line',          is_default: 1 },
  { pattern: 'iTerm',            pattern_type: 'app', classification: 'productive', reason: 'Terminal emulator',     is_default: 1 },
  { pattern: 'iTerm2',           pattern_type: 'app', classification: 'productive', reason: 'Terminal emulator',     is_default: 1 },
  { pattern: 'Warp',             pattern_type: 'app', classification: 'productive', reason: 'Terminal emulator',     is_default: 1 },
  { pattern: 'Ghostty',          pattern_type: 'app', classification: 'productive', reason: 'Terminal emulator',     is_default: 1 },
  { pattern: 'Alacritty',        pattern_type: 'app', classification: 'productive', reason: 'Terminal emulator',     is_default: 1 },
  { pattern: 'Hyper',            pattern_type: 'app', classification: 'productive', reason: 'Terminal emulator',     is_default: 1 },
  { pattern: 'PyCharm',          pattern_type: 'app', classification: 'productive', reason: 'Python IDE',            is_default: 1 },
  { pattern: 'IntelliJ',         pattern_type: 'app', classification: 'productive', reason: 'Java IDE',              is_default: 1 },
  { pattern: 'WebStorm',         pattern_type: 'app', classification: 'productive', reason: 'JS IDE',                is_default: 1 },
  { pattern: 'GoLand',           pattern_type: 'app', classification: 'productive', reason: 'Go IDE',                is_default: 1 },
  { pattern: 'Rider',            pattern_type: 'app', classification: 'productive', reason: '.NET IDE',              is_default: 1 },
  { pattern: 'CLion',            pattern_type: 'app', classification: 'productive', reason: 'C/C++ IDE',             is_default: 1 },
  { pattern: 'RubyMine',         pattern_type: 'app', classification: 'productive', reason: 'Ruby IDE',              is_default: 1 },
  { pattern: 'DataGrip',         pattern_type: 'app', classification: 'productive', reason: 'Database IDE',          is_default: 1 },
  { pattern: 'Android Studio',   pattern_type: 'app', classification: 'productive', reason: 'Android IDE',           is_default: 1 },
  { pattern: 'Sublime Text',     pattern_type: 'app', classification: 'productive', reason: 'Text editor',           is_default: 1 },
  { pattern: 'Zed',              pattern_type: 'app', classification: 'productive', reason: 'Code editor',           is_default: 1 },
  { pattern: 'Nova',             pattern_type: 'app', classification: 'productive', reason: 'Code editor',           is_default: 1 },
  { pattern: 'BBEdit',           pattern_type: 'app', classification: 'productive', reason: 'Text editor',           is_default: 1 },
  { pattern: 'Typora',           pattern_type: 'app', classification: 'productive', reason: 'Markdown editor',       is_default: 1 },
  { pattern: 'Obsidian',         pattern_type: 'app', classification: 'productive', reason: 'Notes',                 is_default: 1 },
  { pattern: 'Notion',           pattern_type: 'app', classification: 'productive', reason: 'Notes & docs',          is_default: 1 },
  { pattern: 'Bear',             pattern_type: 'app', classification: 'productive', reason: 'Notes',                 is_default: 1 },
  { pattern: 'Craft',            pattern_type: 'app', classification: 'productive', reason: 'Notes & docs',          is_default: 1 },
  { pattern: 'Logseq',           pattern_type: 'app', classification: 'productive', reason: 'Knowledge base',        is_default: 1 },
  { pattern: 'Figma',            pattern_type: 'app', classification: 'productive', reason: 'Design tool',           is_default: 1 },
  { pattern: 'Sketch',           pattern_type: 'app', classification: 'productive', reason: 'Design tool',           is_default: 1 },
  { pattern: 'Framer',           pattern_type: 'app', classification: 'productive', reason: 'Design tool',           is_default: 1 },
  { pattern: 'Pixelmator',       pattern_type: 'app', classification: 'productive', reason: 'Image editor',          is_default: 1 },
  { pattern: 'Affinity',         pattern_type: 'app', classification: 'productive', reason: 'Design app',            is_default: 1 },
  { pattern: 'Adobe Photoshop',  pattern_type: 'app', classification: 'productive', reason: 'Image editor',          is_default: 1 },
  { pattern: 'Adobe Illustrator',pattern_type: 'app', classification: 'productive', reason: 'Vector editor',         is_default: 1 },
  { pattern: 'Adobe Premiere',   pattern_type: 'app', classification: 'productive', reason: 'Video editor',          is_default: 1 },
  { pattern: 'After Effects',    pattern_type: 'app', classification: 'productive', reason: 'Motion design',         is_default: 1 },
  { pattern: 'DaVinci Resolve',  pattern_type: 'app', classification: 'productive', reason: 'Video editor',          is_default: 1 },
  { pattern: 'Final Cut',        pattern_type: 'app', classification: 'productive', reason: 'Video editor',          is_default: 1 },
  { pattern: 'Logic Pro',        pattern_type: 'app', classification: 'productive', reason: 'Music production',      is_default: 1 },
  { pattern: 'GarageBand',       pattern_type: 'app', classification: 'productive', reason: 'Music production',      is_default: 1 },
  { pattern: 'Postman',          pattern_type: 'app', classification: 'productive', reason: 'API testing',           is_default: 1 },
  { pattern: 'Insomnia',         pattern_type: 'app', classification: 'productive', reason: 'API testing',           is_default: 1 },
  { pattern: 'Paw',              pattern_type: 'app', classification: 'productive', reason: 'API client',            is_default: 1 },
  { pattern: 'RapidAPI',         pattern_type: 'app', classification: 'productive', reason: 'API client',            is_default: 1 },
  { pattern: 'TablePlus',        pattern_type: 'app', classification: 'productive', reason: 'Database tool',         is_default: 1 },
  { pattern: 'Sequel Pro',       pattern_type: 'app', classification: 'productive', reason: 'Database tool',         is_default: 1 },
  { pattern: 'DB Browser',       pattern_type: 'app', classification: 'productive', reason: 'Database tool',         is_default: 1 },
  { pattern: 'Tower',            pattern_type: 'app', classification: 'productive', reason: 'Git client',            is_default: 1 },
  { pattern: 'Fork',             pattern_type: 'app', classification: 'productive', reason: 'Git client',            is_default: 1 },
  { pattern: 'SourceTree',       pattern_type: 'app', classification: 'productive', reason: 'Git client',            is_default: 1 },
  { pattern: 'GitHub Desktop',   pattern_type: 'app', classification: 'productive', reason: 'Git client',            is_default: 1 },
  { pattern: 'Proxyman',         pattern_type: 'app', classification: 'productive', reason: 'Network debugger',      is_default: 1 },
  { pattern: 'Charles',          pattern_type: 'app', classification: 'productive', reason: 'Network debugger',      is_default: 1 },
  { pattern: 'Simulator',        pattern_type: 'app', classification: 'productive', reason: 'iOS simulator',         is_default: 1 },
  { pattern: 'ScreenFlow',       pattern_type: 'app', classification: 'productive', reason: 'Screen recording',      is_default: 1 },
  { pattern: 'Linear',           pattern_type: 'app', classification: 'productive', reason: 'Project management',    is_default: 1 },
  { pattern: 'Microsoft Word',   pattern_type: 'app', classification: 'productive', reason: 'Word processor',        is_default: 1 },
  { pattern: 'Microsoft Excel',  pattern_type: 'app', classification: 'productive', reason: 'Spreadsheet',           is_default: 1 },
  { pattern: 'Microsoft PowerPoint', pattern_type: 'app', classification: 'productive', reason: 'Presentation',      is_default: 1 },
  { pattern: 'Pages',            pattern_type: 'app', classification: 'productive', reason: 'Word processor',        is_default: 1 },
  { pattern: 'Numbers',          pattern_type: 'app', classification: 'productive', reason: 'Spreadsheet',           is_default: 1 },
  { pattern: 'Keynote',          pattern_type: 'app', classification: 'productive', reason: 'Presentation',          is_default: 1 },
  { pattern: 'TextEdit',         pattern_type: 'app', classification: 'productive', reason: 'Text editor',           is_default: 1 },
  { pattern: 'Notes',            pattern_type: 'app', classification: 'productive', reason: 'Notes',                 is_default: 1 },
  { pattern: 'Reminders',        pattern_type: 'app', classification: 'productive', reason: 'Task manager',          is_default: 1 },

  // ── Neutral apps ──────────────────────────────────────────────────────────
  { pattern: 'Spotify',          pattern_type: 'app', classification: 'neutral',     reason: 'Music (neutral)',       is_default: 1 },
  { pattern: 'Music',            pattern_type: 'app', classification: 'neutral',     reason: 'Music app',            is_default: 1 },
  { pattern: 'Podcasts',         pattern_type: 'app', classification: 'neutral',     reason: 'Podcasts',             is_default: 1 },
  { pattern: 'Messages',         pattern_type: 'app', classification: 'neutral',     reason: 'Messaging',            is_default: 1 },
  { pattern: 'Slack',            pattern_type: 'app', classification: 'neutral',     reason: 'Work chat',            is_default: 1 },
  { pattern: 'Discord',          pattern_type: 'app', classification: 'neutral',     reason: 'Chat platform',        is_default: 1 },
  { pattern: 'Mail',             pattern_type: 'app', classification: 'neutral',     reason: 'Email',                is_default: 1 },
  { pattern: 'Spark',            pattern_type: 'app', classification: 'neutral',     reason: 'Email client',         is_default: 1 },
  { pattern: 'Mimestream',       pattern_type: 'app', classification: 'neutral',     reason: 'Email client',         is_default: 1 },
  { pattern: 'Airmail',          pattern_type: 'app', classification: 'neutral',     reason: 'Email client',         is_default: 1 },
  { pattern: 'Zoom',             pattern_type: 'app', classification: 'neutral',     reason: 'Video calls',          is_default: 1 },
  { pattern: 'Microsoft Teams',  pattern_type: 'app', classification: 'neutral',     reason: 'Video calls',          is_default: 1 },
  { pattern: 'Google Meet',      pattern_type: 'app', classification: 'neutral',     reason: 'Video calls',          is_default: 1 },
  { pattern: 'FaceTime',         pattern_type: 'app', classification: 'neutral',     reason: 'Video calls',          is_default: 1 },
  { pattern: 'Loom',             pattern_type: 'app', classification: 'neutral',     reason: 'Video messaging',      is_default: 1 },
  { pattern: 'Finder',           pattern_type: 'app', classification: 'neutral',     reason: 'File manager',         is_default: 1 },
  { pattern: 'System Preferences',pattern_type:'app', classification: 'neutral',     reason: 'System settings',      is_default: 1 },
  { pattern: 'System Settings',  pattern_type: 'app', classification: 'neutral',     reason: 'System settings',      is_default: 1 },
  { pattern: 'Calculator',       pattern_type: 'app', classification: 'neutral',     reason: 'Utility',              is_default: 1 },
  { pattern: 'Calendar',         pattern_type: 'app', classification: 'neutral',     reason: 'Calendar',             is_default: 1 },
  { pattern: 'Preview',          pattern_type: 'app', classification: 'neutral',     reason: 'Document viewer',      is_default: 1 },
  { pattern: 'Photos',           pattern_type: 'app', classification: 'neutral',     reason: 'Photo library',        is_default: 1 },
  { pattern: '1Password',        pattern_type: 'app', classification: 'neutral',     reason: 'Password manager',     is_default: 1 },
  { pattern: 'Bitwarden',        pattern_type: 'app', classification: 'neutral',     reason: 'Password manager',     is_default: 1 },
  { pattern: 'Alfred',           pattern_type: 'app', classification: 'neutral',     reason: 'Launcher',             is_default: 1 },
  { pattern: 'Raycast',          pattern_type: 'app', classification: 'neutral',     reason: 'Launcher',             is_default: 1 },
];

// Known browser app names for special URL/domain handling
export const BROWSER_APP_NAMES = [
  'Google Chrome',
  'Safari',
  'Firefox',
  'Arc',
  'Brave Browser',
  'Microsoft Edge',
  'Opera',
  'Vivaldi',
];
